#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Read mariadb configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from Environment
config["mariadb_tcp_port"] = os.environ.get("MARIADB_TCP_PORT","")
config["path"] =  os.environ.get("TRAEFIK_PATH","")
config["http2https"] =  os.environ.get("TRAEFIK_HTTP2HTTPS","False") == "True";
config["upload_limit"] =  os.environ.get("UPLOAD_LIMIT","2M").rstrip('M')

# Find the hostname of the node
config["hostname"] = agent.get_hostname()

# Dump the configuratio to stdou
json.dump(config, fp=sys.stdout)
