#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
import os
import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_PATH",
        "TRAEFIK_HTTP2HTTPS"
    ]:
    agent.set_env(evar, original_environment[evar])

# mariadb use the first random port, traefik the second one
env_tcp_ports = os.environ["TCP_PORTS"].split(',')
mariadb_tcp_port = env_tcp_ports[0]
traefik_tcp_port = env_tcp_ports[1]
# Talk with agent using file descriptor.
# Setup configuration from user input.
agent.set_env("MARIADB_TCP_PORT", mariadb_tcp_port)
agent.set_env("TRAEFIK_TCP_PORT", traefik_tcp_port)

agent.dump_env()
